# Generated by Django 2.1.4 on 2019-01-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('Adult', 'Adult'), ('Bussiness', 'Bussiness'), ('Fiction', 'Fiction'), ('Science', 'Science'), ('Bed_Time', 'Bed_Time'), ('Technology', 'Technology'), ('Exam_Preparation', 'Exam_Preparation'), ('Literature', 'Literature')], max_length=20)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
