# Generated by Django 2.1.4 on 2019-01-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190108_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='authors', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.CharField(default='publications', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Bed_Time', 'Bed_Time'), ('Literature', 'Literature'), ('Fiction', 'Fiction'), ('Technology', 'Technology'), ('Exam_Preparation', 'Exam_Preparation'), ('Bussiness', 'Bussiness'), ('Adult', 'Adult'), ('Science', 'Science')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
