# Generated by Django 2.1.4 on 2019-01-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190108_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_taker', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('publication', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Exam_Preparation', 'Exam_Preparation'), ('Fiction', 'Fiction'), ('Bed_Time', 'Bed_Time'), ('Science', 'Science'), ('Bussiness', 'Bussiness'), ('Adult', 'Adult'), ('Technology', 'Technology'), ('Literature', 'Literature')], max_length=20),
        ),
    ]
