# Generated by Django 2.1.4 on 2019-01-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190108_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktaken',
            name='category',
            field=models.CharField(default='catagory', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Literature', 'Literature'), ('Science', 'Science'), ('Bussiness', 'Bussiness'), ('Fiction', 'Fiction'), ('Bed_Time', 'Bed_Time'), ('Adult', 'Adult'), ('Exam_Preparation', 'Exam_Preparation'), ('Technology', 'Technology')], max_length=20),
        ),
    ]
