# Generated by Django 2.1.4 on 2019-01-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20190110_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Adult', 'Adult'), ('Exam_Preparation', 'Exam_Preparation'), ('Bussiness', 'Bussiness'), ('Bed_Time', 'Bed_Time'), ('Technology', 'Technology'), ('Science', 'Science'), ('Literature', 'Literature')], max_length=20),
        ),
    ]
