# Generated by Django 2.1.4 on 2019-01-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20190111_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Literature', 'Literature'), ('Adult', 'Adult'), ('Bussiness', 'Bussiness'), ('Fiction', 'Fiction'), ('Science', 'Science'), ('Bed_Time', 'Bed_Time'), ('Technology', 'Technology'), ('Exam_Preparation', 'Exam_Preparation')], max_length=20),
        ),
    ]
