# Generated by Django 2.1.4 on 2019-01-11 07:27

import accounts.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_taker',
            name='fee_paid',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='book_taker',
            name='member_till',
            field=models.DateField(blank=True, default=accounts.models.member_date),
        ),
        migrations.AlterField(
            model_name='book_taker',
            name='paid_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
